import Head from "next/head";
import Image from "next/image";

import Header from "@components/layout/header";
import Feature from "@components/home/feature";
import Footer from "@components/layout/footer";

export default function Contact() {
  return (
    <>
      <Head>
        <title>Contact</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <section className="relative overflow-hidden bg-gray-50 py-36">
        <img
          className="absolute bottom-0 right-0"
          src="flaro-assets/images/contact/gradient2.svg"
          alt=""
        />
        <div className="container relative z-10 mx-auto px-4">
          <div className="-m-8 flex flex-wrap">
            <div className="w-full p-8 md:w-1/2">
              <div className="flex h-full flex-col justify-between">
                <div className="mb-12 block md:max-w-md">
                  <p className="tracking-px mb-6 text-sm font-bold uppercase text-indigo-600">
                    Contact us
                  </p>
                  <h2 className="xl:text-10xl font-heading tracking-px-n text-6xl font-bold leading-none md:text-8xl">
                    Get connected to grow better business.
                  </h2>
                </div>
                <div className="block">
                  <p className="tracking-px mb-4 text-sm font-bold uppercase text-gray-400">
                    Email
                  </p>
                  <ul className="mb-14">
                    <li className="text-xl font-semibold leading-normal">
                      info@email.com
                    </li>
                    <li className="text-xl font-semibold leading-normal">
                      support@gmail.com
                    </li>
                  </ul>
                  <p className="tracking-px mb-4 text-sm font-bold uppercase text-gray-400">
                    Phone
                  </p>
                  <ul>
                    <li className="text-xl font-semibold leading-normal">
                      +1 848 4125 690
                    </li>
                    <li className="text-xl font-semibold leading-normal">
                      +1 848 4125 658
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <div className="w-full p-8 md:w-1/2">
              <form className="rounded-4xl shadow-12xl ml-auto bg-white bg-opacity-80 px-11 pt-8 pb-12 md:max-w-xl">
                <label className="mb-4 block">
                  <p className="mb-2 font-semibold leading-normal text-gray-900">
                    Name
                  </p>
                  <div className="relative">
                    <svg
                      className="absolute left-4 top-1/2 -translate-y-1/2 transform"
                      width="20"
                      height="26"
                      viewBox="0 0 20 26"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M13.3327 8.83358C13.3327 10.6745 11.8403 12.1669 9.99935 12.1669C8.1584 12.1669 6.66602 10.6745 6.66602 8.83358C6.66602 6.99263 8.1584 5.50024 9.99935 5.50024C11.8403 5.50024 13.3327 6.99263 13.3327 8.83358Z"
                        stroke="#9CA3AF"
                        strokeWidth="1.5"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      ></path>
                      <path
                        d="M9.99935 14.6669C6.77769 14.6669 4.16602 17.2786 4.16602 20.5002H15.8327C15.8327 17.2786 13.221 14.6669 9.99935 14.6669Z"
                        stroke="#9CA3AF"
                        strokeWidth="1.5"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      ></path>
                    </svg>
                    <input
                      className="w-full rounded-lg border border-gray-300 py-3 pl-12 pr-4 font-medium text-gray-500 placeholder-gray-500 outline-none focus:ring focus:ring-indigo-300"
                      id="contactInput3-1"
                      type="text"
                      placeholder="First &amp; last name"
                    />
                  </div>
                </label>
                <label className="mb-4 block">
                  <p className="mb-2 font-semibold leading-normal text-gray-900">
                    Email Address
                  </p>
                  <div className="relative">
                    <svg
                      className="absolute left-4 top-1/2 -translate-y-1/2 transform"
                      width="20"
                      height="26"
                      viewBox="0 0 20 26"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M13.3327 8.83358C13.3327 10.6745 11.8403 12.1669 9.99935 12.1669C8.1584 12.1669 6.66602 10.6745 6.66602 8.83358C6.66602 6.99263 8.1584 5.50024 9.99935 5.50024C11.8403 5.50024 13.3327 6.99263 13.3327 8.83358Z"
                        stroke="#9CA3AF"
                        strokeWidth="1.5"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      ></path>
                      <path
                        d="M9.99935 14.6669C6.77769 14.6669 4.16602 17.2786 4.16602 20.5002H15.8327C15.8327 17.2786 13.221 14.6669 9.99935 14.6669Z"
                        stroke="#9CA3AF"
                        strokeWidth="1.5"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      ></path>
                    </svg>
                    <input
                      className="w-full rounded-lg border border-gray-300 py-3 pl-12 pr-4 font-medium text-gray-500 placeholder-gray-500 outline-none focus:ring focus:ring-indigo-300"
                      id="contactInput3-2"
                      type="text"
                      placeholder="Email address"
                    />
                  </div>
                </label>
                <label className="block">
                  <p className="mb-2 font-semibold leading-normal text-gray-900">
                    Message
                  </p>
                  <div className="relative">
                    <svg
                      className="absolute left-4 top-4"
                      width="20"
                      height="26"
                      viewBox="0 0 20 26"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M13.3327 8.83358C13.3327 10.6745 11.8403 12.1669 9.99935 12.1669C8.1584 12.1669 6.66602 10.6745 6.66602 8.83358C6.66602 6.99263 8.1584 5.50024 9.99935 5.50024C11.8403 5.50024 13.3327 6.99263 13.3327 8.83358Z"
                        stroke="#9CA3AF"
                        strokeWidth="1.5"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      ></path>
                      <path
                        d="M9.99935 14.6669C6.77769 14.6669 4.16602 17.2786 4.16602 20.5002H15.8327C15.8327 17.2786 13.221 14.6669 9.99935 14.6669Z"
                        stroke="#9CA3AF"
                        strokeWidth="1.5"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      ></path>
                    </svg>
                    <textarea
                      className="mb-6 h-48 w-full resize-none rounded-lg border border-gray-300 p-4 px-12 font-medium text-gray-500 placeholder-gray-500 outline-none focus:ring focus:ring-indigo-300"
                      id="contactInput3-3"
                      placeholder="Write message"
                    ></textarea>
                    <div className="md:inline-block">
                      <button
                        className="shadow-4xl w-full rounded-xl border border-indigo-700 bg-indigo-600 py-4 px-9 font-semibold text-white transition duration-200 ease-in-out hover:bg-indigo-700 focus:ring focus:ring-indigo-300"
                        type="button"
                      >
                        Send Message
                      </button>
                    </div>
                  </div>
                </label>
              </form>
            </div>
          </div>
        </div>
      </section>

      <section className="relative overflow-hidden bg-white pt-24 pb-36">
        <div className="container relative z-10 mx-auto px-4">
          <div className="-m-3 flex flex-wrap">
            <div className="w-full p-3 md:w-1/3">
              <div className="border-blueGray-100 shadow-11xl h-full rounded-xl border bg-white bg-opacity-90 p-11 text-center">
                <div className="relative mx-auto mb-6 h-16 w-16 rounded-full bg-indigo-600">
                  <div className="absolute left-1/2 top-1/2 -translate-y-1/2 -translate-x-1/2 transform">
                    <svg
                      width="32"
                      height="33"
                      viewBox="0 0 32 33"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M4 11.1666L14.5208 18.1805C15.4165 18.7776 16.5835 18.7776 17.4792 18.1805L28 11.1666M6.66667 25.8333H25.3333C26.8061 25.8333 28 24.6394 28 23.1666V9.83329C28 8.36053 26.8061 7.16663 25.3333 7.16663H6.66667C5.19391 7.16663 4 8.36053 4 9.83329V23.1666C4 24.6394 5.19391 25.8333 6.66667 25.8333Z"
                        stroke="white"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      ></path>
                    </svg>
                  </div>
                </div>
                <h3 className="font-heading mb-3 text-xl font-bold leading-snug">
                  Send Email
                </h3>
                <p className="font-medium leading-relaxed">info@mail.com</p>
                <p className="font-medium leading-relaxed">support@mail.com</p>
              </div>
            </div>
            <div className="w-full p-3 md:w-1/3">
              <div className="border-blueGray-100 shadow-11xl h-full rounded-xl border bg-white bg-opacity-90 p-11 text-center">
                <div className="border-blueGray-200 relative mx-auto mb-6 h-16 w-16 rounded-full border bg-white">
                  <div className="absolute left-1/2 top-1/2 -translate-y-1/2 -translate-x-1/2 transform">
                    <svg
                      width="32"
                      height="33"
                      viewBox="0 0 32 33"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M4 7.16667C4 5.69391 5.19391 4.5 6.66667 4.5H11.039C11.6129 4.5 12.1224 4.86724 12.3039 5.4117L14.301 11.4029C14.5108 12.0324 14.2258 12.7204 13.6324 13.0172L10.6227 14.522C12.0923 17.7816 14.7184 20.4077 17.978 21.8773L19.4828 18.8676C19.7796 18.2742 20.4676 17.9892 21.0971 18.199L27.0883 20.1961C27.6328 20.3776 28 20.8871 28 21.461V25.8333C28 27.3061 26.8061 28.5 25.3333 28.5H24C12.9543 28.5 4 19.5457 4 8.5V7.16667Z"
                        stroke="#4F46E5"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      ></path>
                    </svg>
                  </div>
                </div>
                <h3 className="font-heading mb-3 text-xl font-bold leading-snug">
                  Call Us
                </h3>
                <p className="font-medium leading-relaxed">+1 8408 412 569</p>
                <p className="font-medium leading-relaxed">+1 8408 412 569</p>
              </div>
            </div>
            <div className="w-full p-3 md:w-1/3">
              <div className="border-blueGray-100 shadow-11xl h-full rounded-xl border bg-white bg-opacity-90 p-11 text-center">
                <div className="border-blueGray-200 relative mx-auto mb-6 h-16 w-16 rounded-full border bg-white">
                  <div className="absolute left-1/2 top-1/2 -translate-y-1/2 -translate-x-1/2 transform">
                    <svg
                      width="32"
                      height="33"
                      viewBox="0 0 32 33"
                      fill="none"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        d="M23.5431 22.7091C22.1797 24.0725 19.192 27.0602 17.4133 28.8389C16.6323 29.62 15.3693 29.6203 14.5883 28.8392C12.8393 27.0903 9.91373 24.1647 8.45818 22.7091C4.29259 18.5435 4.29259 11.7898 8.45818 7.62419C12.6238 3.4586 19.3775 3.4586 23.5431 7.62419C27.7087 11.7898 27.7087 18.5435 23.5431 22.7091Z"
                        stroke="#4F46E5"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      ></path>
                      <path
                        d="M20.0007 15.1667C20.0007 17.3758 18.2098 19.1667 16.0007 19.1667C13.7915 19.1667 12.0007 17.3758 12.0007 15.1667C12.0007 12.9575 13.7915 11.1667 16.0007 11.1667C18.2098 11.1667 20.0007 12.9575 20.0007 15.1667Z"
                        stroke="#4F46E5"
                        strokeWidth="2"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      ></path>
                    </svg>
                  </div>
                </div>
                <h3 className="font-heading mb-3 text-xl font-bold leading-snug">
                  Address
                </h3>
                <p className="mx-auto max-w-xs font-medium leading-relaxed">
                  380 St Kilda Road, Melbourne VIC 3004, Australia
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </>
  );
}
